"""empty message

Revision ID: 4c832a71f7c5
Revises: f915d0f83cc6
Create Date: 2022-08-07 17:58:23.099888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c832a71f7c5'
down_revision = 'f915d0f83cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'looking_for_talent')
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('venues', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_talent')
    op.add_column('artists', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###
