"""empty message

Revision ID: aed4eb8cad85
Revises: e11d907490b6
Create Date: 2022-08-08 15:45:11.566762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed4eb8cad85'
down_revision = 'e11d907490b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shows', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.alter_column('shows', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shows', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
